#x=input("enter a no")
#print(x)
#print(type(x))
a=int(10)
b=int(20)
print(a+b)
n=float(input("enter radius\n"))
print((3.14)*(n*n))
circumference=2*3.14*n
print(f"circum:{circumference:.2f}")