sn=int(input("enter the student no"))
sname=input("enter the name of the student")
math=int(input("enter math marks"))
phy=int(input("enter phy marks"))
chem=int(input("enter chem marks"))
t=math+phy+chem
avg=t/3.0
print("student no:",sn)
print("student name:",sname)
print("math marks:",math)
print("physics marks:",phy)
print("chem marks:",chem)
print("total marks:",t)
#print(f"average marks:{avg:.2f}")
print(round(avg,2))